<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.38.0" />
    <PackageReference Include="Microsoft.Graph.Communications.Calls">
      <Version>1.2.0.850</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Skype.Bots.Media" Version="1.30.0.19-preview" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>
